version: '3.8'

services:
  beauty-parlor-salon-prod:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./compose/prod/Dockerfile
    image: "${ECR_IMAGE}"
    container_name: beauty-parlor-salon-prod
    ports:
      - "9000:8080"
    tty: true
    stdin_open: true

  beauty-parlor-salon-dev:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    image: beauty-parlor-salon-dev:latest
    container_name: beauty-parlor-salon-dev
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - "8000:8000"
