version: '3.8'

services:
  web:
    platform: linux/amd64
    build:
      dockerfile: Dockerfile.dev
    ports:
      - '80:80'

    # mount location
    volumes:
      - '.:/work'

    tty: true
    stdin_open: true
