version: '3.8'

services:
  db:
    image: "mysql:8.0"
    container_name: "mysql_db"
    # env_file: .env
    restart: always
    healthcheck:
      test: "exit 0"
    ports:
      - "3306:3306"
    volumes:
      - db-data-mysql_db:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    tty: true
    stdin_open: true

volumes:
  db-data-mysql_db:
    
